Fix build error due to strncpy bounds
This error is fatal with recent GCC versions:
mkbootimg.c:380:9: error: ‘strncpy’ specified bound 1024 equals destination size